export enum GroupError {
  GROUP_EXIST_EXCEPTION = "GROUP_EXIST_EXCEPTION",
  GROUP_NOT_FOUND_EXCEPTION = "GROUP_NOT_FOUND_EXCEPTION",
  GROUP_NAME_MACHINE_IS_BROKEN_EXCEPTION = "GROUP_NAME_MACHINE_IS_BROKEN_EXCEPTION"
}

export enum DirectMessageError {
  DIRECT_MESSAGE_EXIST_EXCEPTION = "DIRECT_MESSAGE_EXIST_EXCEPTION",
  DIRECT_MESSAGE_NOT_FOUND_EXCEPTION = "DIRECT_MESSAGE_NOT_FOUND_EXCEPTION"
}
