enum WorkspaceMemberError {
  WORKSPACE_MEMBER_PREMISSION_EXCEPTION = "WORKSPACE_MEMBER_PREMISSION_EXCEPTION",
  WORKSPACE_MEMBER_NOT_FOUND_EXCEPTION = "WORKSPACE_MEMBER_NOT_FOUND_EXCEPTION",
  WORKSPACE_MEMBER_EXIST_EXCEPTION = "WORKSPACE_MEMBER_EXIST_EXCEPTION",
  NOT_WORKSPACE_MEMBER_EXCEPTION = "NOT_WORKSPACE_MEMBER_EXCEPTION"
}

export default WorkspaceMemberError;
