enum RegistryError {
  MISSING_CREDITIONAL_EXCEPTION = "MISSING_CREDITIONAL_EXCEPTION",
  DOMAIN_REGISTRATION_EXCEPTION = "DOMAIN_REGISTRATION_EXCEPTION",
  REGISTRATION_EXIST_EXCEPTION = "REGISTRATION_EXIST_EXCEPTION",
  ADMIN_REGISTRATION_EXCEPTION = "ADMIN_REGISTRATION_EXCEPTION",
  ADMIN_MEMBER_EXIST_EXCEPTION = "ADMIN_MEMBER_EXIST_EXCEPTION",
  NO_ORIGIN_EXCEPTION = "NO_ORIGIN_EXCEPTION",
  DOMAIN_EXCEPTION = "DOMAIN_EXCEPTION"
}

export default RegistryError;
