enum WroskapceError {
  WORKSPACE_DESCRIPTION_CHARACTER_LIMIT = "WORKSPACE_DESCRIPTION_CHARACTER_LIMIT",
  WORKSPACE_NOT_FOUND_EXCEPTION = "WORKSPACE_NOT_FOUND_EXCEPTION",
  WORKSPACE_ARCHIVED_EXCEPTION = "WORKSPACE_ARCHIVED_EXCEPTION",
  WORKSPACE_SECTION_EXECPTION = "WORKSPACE_SECTION_EXECPTION",
  WORKSPACE_EXIST_EXCEPTION = "WORKSPACE_EXIST_EXCEPTION"
}

export default WroskapceError;
