version: 2

workflows:
  version: 2
  test_and_deploy:
    jobs:
      - test
      - deploy:
          requires:
            - test
          filters:
            branches:
              only:
                - dev
                - master
                - staging

jobs:
  test:
    docker:
      - image: circleci/node:8.9.1
      - image: circleci/mongo:3.6.2

    environment:
      API_KEY: FOOBARBAZ
      HOST: http://localhost:8081
      JSON_WEB_TOKEN: SPOODER_MAN
      NO_REPLY: Pivot <no-reply@pivotlms.com>
      MONGO_URI: mongodb://localhost:27017/pivot

    steps:
      - checkout

      - run:
          name: npm install
          command: npm i

      - run:
          name: npm run build
          command: npm run build

      # - run:
      #     name: npm test
      #     command: npm test

  deploy:
    docker:
      - image: circleci/node:8.9.1
      - image: docker:17.05.0-ce-git

    steps:
      - checkout
      - setup_remote_docker

      - run:
          name: Building docker image
          environment:
            HOST: https://pivotlms-api.herokuapp.com
            HOST_DEV: https://pivotlms-api-dev.herokuapp.com
          command: |
            export SHORT_SHA=$(git rev-parse --short HEAD)

            case $CIRCLE_BRANCH in
              master )
                docker build -t pivotlms-api:$CIRCLE_BRANCH-$SHORT_SHA \
                --build-arg NODE_ENV=prod \
                --build-arg GIT_SHA=$SHORT_SHA \
                --build-arg AWS_S3_BUCKET=pivot \
                --build-arg HOST=$HOST .
                ;;
              *)
                docker build -t pivotlms-api:$CIRCLE_BRANCH-$SHORT_SHA \
                --build-arg NODE_ENV=dev \
                --build-arg GIT_SHA=$SHORT_SHA \
                --build-arg AWS_S3_BUCKET=pivot \
                --build-arg HOST=$HOST_DEV .
                ;;
            esac

      - run:
          name: Pushing docker image to heroku container registry
          environment:
            HEROKU_USERNAME: andreGarvin
          command: |
            export SHORT_SHA=$(git rev-parse --short HEAD)
            export SERVICE_NAME=pivotlms-api-$CIRCLE_BRANCH

            echo $HEROKU_API_KEY > apikey

            cat apikey | docker login --username=$HEROKU_USERNAME --password-stdin registry.heroku.com

            docker tag pivotlms-frontend:$CIRCLE_BRANCH-$SHORT_SHA registry.heroku.com/$SERVICE_NAME/web

            docker push registry.heroku.com/$SERVICE_NAME/web

      - run:
          name: Releasing docker image to heroku
          command: |
            export SERVICE_NAME=pivotlms-api-$CIRCLE_BRANCH
            export IMAGE_NAME=registry.heroku.com/$SERVICE_NAME/web
            export IMAGE_ID=$(docker inspect $IMAGE_NAME --format={{.Id}})

            echo "Releasing = $IMAGE_NAME [$IMAGE_ID]"

            curl -n -X PATCH https://api.heroku.com/apps/$SERVICE_NAME/formation \
              -d '{ "updates": [ { "type": "web", "docker_image": '\"$IMAGE_ID\"' } ] }' \
              -H "Accept: application/vnd.heroku+json; version=3.docker-releases" \
              -H "Authorization: Bearer $HEROKU_API_KEY" \
              -H "Content-Type: application/json"
