version: 2

workflows:
  version: 2
  test_and_deploy:
    jobs:
      - test
      - deploy:
          requires:
            - test

jobs:
  test:
    docker:
      - image: circleci/node:8.9.1
      - image: circleci/mongo:3.6.2

    environment:
      # This is not sensitive secrets
      API_KEY: FOOBARBAZ
      HOST: http://localhost:8081
      JSON_WEB_TOKEN: SPOODER_MAN
      NO_REPLY: Pivot <no-reply@pivotlms.com>
      MONGO_URI: mongodb://localhost:27017/pivot

    steps:
      - checkout

      - run:
          name: npm install
          command: npm i

      - run:
          name: npm run build
          command: npm run build

      # - run:
      #     name: npm test
      #     command: npm test

  deploy:
    docker:
      - image: circleci/node:8.9.1
      - image: docker:17.05.0-ce-git

    environment:
      APP_NAME: pivotlms-api

    steps:
      - checkout
      - setup_remote_docker

      - run:
          name: pre-flight deployment check
          command: |
            if [ "${#CIRCLE_BRANCH}" -gt "10" ]
            then
              echo "Branch name '$CIRCLE_BRANCH' is too long, change the name of the branch to be less then 10 characters"
              exit 1
            fi

      - run:
          name: Building docker image
          command: |
            chmod u+x scripts/build.sh

            scripts/build.sh --branch $CIRCLE_BRANCH --app $APP_NAME

      - run:
          name: Pushing docker image to heroku container registry

          environment:
            USER_LOGIN: andreGarvin

          command: |
            chmod u+x scripts/publish.sh

            echo "$HEROKU_API_KEY" > apikey

            cat apikey | scripts/publish.sh --password-stdin --user-login $USER_LOGIN --app $APP_NAME --branch $CIRCLE_BRANCH --create

      - run:
          name: Releasing docker image to heroku
          command: |
            chmod u+x scripts/deploy.sh

            echo "$HEROKU_API_KEY" > apikey

            cat apikey | scripts/deploy.sh --password-stdin --app $APP_NAME --branch $CIRCLE_BRANCH
