enum InvitationError {
  INSUFFICIENT_INVITATION_COUNT_EXCEPTION = "INSUFFICIENT_INVITATION_COUNT_EXCEPTION",
  INVITATION_BATCH_FAILED_EXCEPTION = "INVITATION_BATCH_FAILED_EXCEPTION",
  INVITATION_PREMISSION_EXCEPTION = "INVITATION_PREMISSION_EXCEPTION",
  INVITATION_TYPE_ASSIGNMENT = "INVITATION_TYPE_ASSIGNMENT_EXCEPTION",
  INVITATION_NOT_FOUND_EXCEPTION = "INVITATION_NOT_FOUND_EXCEPTION",
  INVITATION_EXIST_EXCEPTION = "INVITATION_EXIST_EXCEPTION",
  DOMAIN_EXCEPTION = "DOMAIN_EXCEPTION"
}

export default InvitationError;
