enum WorkspaceMemberRequestError {
  WORKSPACE_MEMBER_REQUEST_NOT_FOUND_EXCEPTION = "WORKSPACE_MEMBER_REQUEST_NOT_FOUND_EXCEPTION",
  WORKSPACE_MEMBER_REQUEST_EXIST_EXECPTION = "WORKSPACE_MEMBER_REQUEST_EXIST_EXECPTION"
}

export default WorkspaceMemberRequestError;
