enum GoogleOauthError {
  OAUTH_STATE_EMAIL_INVALID_EXCEPTION = "OAUTH_STATE_EMAIL_INVALID_EXCEPTION",
  USER_NOT_FOUND_EXCEPTION = "USER_NOT_FOUND_EXCEPTION",
  FAILED_OAUTH_EXCEPTION = "FAILED_OAUTH_EXCEPTION"
}

export default GoogleOauthError;
