export const catBreeds = [
  "Abyssinian",
  "Aegean",
  "American Curl",
  "American Bobtail",
  "American Shorthair",
  "American Wirehair",
  "Aphrodite Giant",
  "Arabian Mau",
  "Australian Mist",
  "Asian",
  "Asian Semi-longhair",
  "Balinese",
  "Bambino",
  "Bengal",
  "Birman",
  "Bombay",
  "Brazilian Shorthair",
  "British Semi-longhair",
  "British Shorthair",
  "British Longhair",
  "Burmese",
  "Burmilla",
  "California Spangled",
  "Chantilly-Tiffany",
  "Chartreux",
  "Chausie",
  "Cheetoh",
  "Colorpoint Shorthair",
  "Cornish Rex",
  "Cymric",
  "Cyprus",
  "Devon Rex",
  "Donskoy",
  "Dragon Li",
  "Dwelf",
  "Egyptian Mau",
  "European Shorthair",
  "Exotic Shorthair",
  "Foldex",
  "German Rex",
  "Havana Brown",
  "Highlander",
  "Himalayan",
  "Japanese Bobtail",
  "Javanese",
  "Karelian Bobtail",
  "Khao Manee",
  "Korat",
  "Korean Bobtail",
  "Korn Ja",
  "Kurilian Bobtail",
  "LaPerm",
  "Lykoi",
  "Maine Coon",
  "Manx",
  "Mekong Bobtail",
  "Minskin",
  "Munchkin",
  "Nebelung",
  "Napoleon",
  "Norwegian Forest cat",
  "Ocicat",
  "Ojos Azules",
  "Oregon Rex",
  "Oriental Bicolor",
  "Oriental Shorthair",
  "Oriental Longhair",
  "Peterbald",
  "Pixie-bob",
  "Raas",
  "Ragamuffin",
  "Ragdoll",
  "Russian Blue",
  "Sam Sawet",
  "Savannah",
  "Scottish Fold",
  "Selkirk Rex",
  "Serengeti",
  "Serrade petit",
  "Siamese",
  "Siberian",
  "Singapura",
  "Snowshoe",
  "Sokoke",
  "Somali",
  "Sphynx",
  "Suphalak",
  "Thai",
  "Thai Lilac",
  "Tonkinese",
  "Toyger",
  "Turkish Angora",
  "Turkish Van",
  "Ukrainian Levkoy",
  "Wila Krungthep",
  "York Chocolate",
  "Manx Longhair",
  "Don Sphynx",
  "Colorpoint Persian",
  "Colorpoint Longhair",
  "Kuril Islands Bobtail",
  "Foreign Longhair",
  "Mandarin",
  "British Angora",
  "Liebling",
  "Russian Black",
  "Russian Tabby",
  "Siberian Forest Cat",
  "Neva Masquerade",
  "Siamese",
  "Wichien Maat"
];

export const words = [
  "midnight",
  "yard",
  "boat",
  "belly",
  "miserable",
  "free",
  "fast",
  "emphasis",
  "positive",
  "star",
  "friendly",
  "favour",
  "production",
  "jest",
  "solo",
  "advertising",
  "formal",
  "posionous",
  "executive",
  "breeze",
  "junior",
  "young",
  "kid",
  "screaming",
  "message",
  "composer",
  "wriggle",
  "wiggler",
  "acceptable",
  "studio",
  "employee",
  "feminist",
  "expressive",
  "retirement",
  "lifestyle",
  "laundry",
  "election",
  "ballot",
  "colorful",
  "tourist",
  "energy",
  "active",
  "neighborhood",
  "winner",
  "vegetable",
  "valley",
  "sigh",
  "hilarious",
  "sleeping"
];
