enum UserError {
  USERNAME_EXIST_EXCEPTION = "USERNAME_EXIST_EXCEPTION",
  ACTION_DENIDED_EXECPTION = "ACTION_DENIDED_EXECPTION",
  USER_NOT_FOUND_EXCEPTION = "USER_NOT_FOUND_EXCEPTION"
}

export default UserError;
