enum UserError {
  MAX_USERNAME_LENGTH_EXCEPTION = "MAX_USERNAME_LENGTH_EXCEPTION",
  USERNAME_EXIST_EXCEPTION = "USERNAME_EXIST_EXCEPTION",
  USER_NOT_FOUND_EXCEPTION = "USER_NOT_FOUND_EXCEPTION"
}

export default UserError;
