export const VALIDATION_EXCEPTION = "VALIDATION_EXCEPTION";

export const INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR";

export enum FileError {
  INVALID_FILE_EXCEPTION = "INVALID_FILE_EXCEPTION",
  EMPTY_FILE_EXCEPTION = "EMPTY_FILE_EXCEPTION",
  CSV_FILE_EXCEPTION = "CSV_FILE_EXCEPTION"
}
